name: LaTeX build and publish

on:
  push:
    branches:
      - ${{ github.event.inputs.branch }}

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: thubo/latexmk:medium

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Compile LaTeX
        run: cd ${{ github.event.inputs.dir }} && latexmk ${{ github.event.inputs.latexmk_args }} ${{ github.event.inputs.filename }}.tex

      - name: Publish PDF
        run: |
          mkdir public
          cp ${{ github.event.inputs.dir }}/${{ github.event.inputs.filename }}.pdf public/main.pdf
          echo '<a href="main.pdf" target="_blank">PDF.</a>' > public/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: public/main.pdf

