name: LaTeX build and publish

on:
  workflow_call:
    inputs:
      dir:
        required: false
        default: '.'
        type: string
      filename:
        required: false
        default: 'main'
        type: string
      latexmk_args:
        required: false
        default: '-pdf'
        type: string
      image:
        required: false
        default: 'medium'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: thubo/latexmk:${{ inputs.image }}
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        run: cd ${{ inputs.dir }} && latexmk ${{ inputs.latexmk_args }} ${{ inputs.filename }}.tex

      - name: Publish PDF
        run: |
          mkdir public
          cp ${{ inputs.dir }}/${{ inputs.filename }}.pdf public/main.pdf
          echo '<a href="main.pdf" target="_blank">PDF.</a>' > public/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: public/main.pdf

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
